################################################################################
# Environment script generated by ilcsoft-install on Thu Dec 12 18:12:55 2013
# for Eutelescope located at [ /remote/pcatlas62/testbeam/ilcsoft/v01-17-03/Eutelescope/v00-09-02 ]
################################################################################


#--------------------------------------------------------------------------------
#     Global Environment Variables
#--------------------------------------------------------------------------------
export MAKEOPTS="-j4"
export CXX="g++-4.6"
export ILCSOFT_CMAKE="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/ILCSoft.cmake"
export CC="gcc-4.6"
export FC="gfortran"
export ILCSOFT_CMAKE_ENV="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/ILCSoft.cmake.env.sh"


#--------------------------------------------------------------------------------
#     Eutelescope
#--------------------------------------------------------------------------------
export EUDAQ="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/Eutelescope/v00-09-02/external/eudaq/tags/v01-00-00"
export MILLEPEDEII="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/Eutelescope/v00-09-02/external/millepede2/tags/V04-00-02"
export MILLEPEDEII_VERSION="tags/V04-00-02"
export EUDAQ_VERSION="tags/v01-00-00"
export EUTELESCOPE="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/Eutelescope/v00-09-02"
export PATH="$MILLEPEDEII:$EUTELESCOPE/bin:$PATH"
export LD_LIBRARY_PATH="$EUTELESCOPE/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     GEAR
#--------------------------------------------------------------------------------
export GEAR="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/gear/v01-03-01"
export PATH="$GEAR/tools:$GEAR/bin:$PATH"
export LD_LIBRARY_PATH="$GEAR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     ROOT
#--------------------------------------------------------------------------------
export ROOTSYS="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/root/5.34.05"
export PATH="$ROOTSYS/bin:$PATH"
export LD_LIBRARY_PATH="$ROOTSYS/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CLHEP
#--------------------------------------------------------------------------------
export CLHEP="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/CLHEP/2.1.3.1"
export CLHEP_BASE_DIR="$CLHEP"
export CLHEP_INCLUDE_DIR="$CLHEP/include"
export PATH="$CLHEP_BASE_DIR/bin:$PATH"
export LD_LIBRARY_PATH="$CLHEP_BASE_DIR/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     RAIDA
#--------------------------------------------------------------------------------
export RAIDA_HOME="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/RAIDA/v01-06-02"
export PATH="$RAIDA_HOME/bin:$PATH"


#--------------------------------------------------------------------------------
#     Marlin
#--------------------------------------------------------------------------------
export MARLIN="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/Marlin/v01-05"
export PATH="$MARLIN/bin:$PATH"
export MARLIN_DLL="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/Eutelescope/v00-09-02/lib/libEutelescope.so:$MARLIN_DLL"


#--------------------------------------------------------------------------------
#     LCCD
#--------------------------------------------------------------------------------
export LCCD="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/lccd/v01-03"


#--------------------------------------------------------------------------------
#     LCIO
#--------------------------------------------------------------------------------
export LCIO="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/lcio/v02-04-02"
export PATH="$LCIO/tools:$LCIO/bin:$PATH"
export LD_LIBRARY_PATH="$LCIO/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     GSL
#--------------------------------------------------------------------------------
export GSL_HOME="/usr"


#--------------------------------------------------------------------------------
#     CED
#--------------------------------------------------------------------------------
export PATH="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/CED/v01-09-01/bin:$PATH"


#--------------------------------------------------------------------------------
#     GBL
#--------------------------------------------------------------------------------
export GBL="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/GBL/V01-15-03"
export LD_LIBRARY_PATH="$GBL/lib:$LD_LIBRARY_PATH"


#--------------------------------------------------------------------------------
#     CMake
#--------------------------------------------------------------------------------


#--------------------------------------------------------------------------------
#     ILCUTIL
#--------------------------------------------------------------------------------
export ilcutil="/remote/pcatlas62/testbeam/ilcsoft/v01-17-03/ilcutil/v01-01"
export LD_LIBRARY_PATH="$ilcutil/lib:$LD_LIBRARY_PATH"
# --- additional comands ------- 
